# Generated by Django 6.0.3 on 2026-03-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('start', '启动'), ('stop', '停止'), ('pause', '暂停'), ('resume', '恢复'), ('config', '配置修改'), ('control', '遥控操作')], max_length=20, verbose_name='操作类型')),
                ('details', models.TextField(blank=True, verbose_name='操作详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '设备操作日志',
                'verbose_name_plural': '设备操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RobotDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='设备唯一标识')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='制造商')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='序列号')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('working', '工作中'), ('charging', '充电中'), ('error', '故障')], default='offline', max_length=20, verbose_name='状态')),
                ('run_mode', models.CharField(choices=[('auto', '自动模式'), ('manual', '手动模式'), ('scheduled', '定时任务模式')], default='auto', max_length=20, verbose_name='运行模式')),
                ('battery_level', models.IntegerField(default=0, verbose_name='电量百分比')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='纬度')),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='经度')),
                ('spray_rate', models.FloatField(default=1.0, verbose_name='喷洒速率(L/min)')),
                ('patrol_interval', models.IntegerField(default=60, verbose_name='巡检间隔(分钟)')),
                ('obstacle_avoidance_sensitivity', models.IntegerField(default=50, verbose_name='避障灵敏度')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '机器人设备',
                'verbose_name_plural': '机器人设备',
                'ordering': ['-registered_at'],
            },
        ),
    ]
