# Generated by Django 6.0.3 on 2026-03-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_analysis', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticalreport',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='devices.robotdevice', verbose_name='设备'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='devices.robotdevice', verbose_name='设备'),
        ),
    ]
