# Generated by Django 6.0.3 on 2026-03-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', '接收'), ('outbound', '发送')], max_length=20, verbose_name='方向')),
                ('message_type', models.CharField(max_length=50, verbose_name='消息类型')),
                ('content', models.TextField(verbose_name='内容')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
            ],
            options={
                'verbose_name': '消息日志',
                'verbose_name_plural': '消息日志',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RobotConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='机器人IP地址')),
                ('port', models.IntegerField(default=8888, verbose_name='端口号')),
                ('is_connected', models.BooleanField(default=False, verbose_name='是否连接')),
                ('connected_at', models.DateTimeField(blank=True, null=True, verbose_name='连接时间')),
                ('disconnected_at', models.DateTimeField(blank=True, null=True, verbose_name='断开时间')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='最后消息时间')),
                ('message_count', models.IntegerField(default=0, verbose_name='消息计数')),
            ],
            options={
                'verbose_name': '机器人连接',
                'verbose_name_plural': '机器人连接',
            },
        ),
    ]
