# Generated by Django 6.0.3 on 2026-03-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotconnection',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='devices.robotdevice', verbose_name='设备'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='communication.robotconnection', verbose_name='连接'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['connection', '-timestamp'], name='communicati_connect_5d9807_idx'),
        ),
    ]
