# Generated by Django 6.0.3 on 2026-03-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropWeedDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_count', models.IntegerField(default=0, verbose_name='作物数量')),
                ('weed_count', models.IntegerField(default=0, verbose_name='杂草数量')),
                ('density_map', models.JSONField(blank=True, null=True, verbose_name='密度分布图')),
                ('detection_boxes', models.JSONField(blank=True, null=True, verbose_name='检测框数据')),
            ],
            options={
                'verbose_name': '作物杂草检测结果',
                'verbose_name_plural': '作物杂草检测结果',
            },
        ),
        migrations.CreateModel(
            name='MaturityDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maturity_level', models.CharField(choices=[('immature', '未成熟'), ('semi_mature', '半成熟'), ('mature', '成熟'), ('over_mature', '过熟')], max_length=20, verbose_name='成熟度等级')),
                ('maturity_percentage', models.FloatField(blank=True, null=True, verbose_name='成熟度百分比')),
                ('fruit_count', models.IntegerField(default=0, verbose_name='果实数量')),
                ('detection_boxes', models.JSONField(blank=True, null=True, verbose_name='检测框数据')),
            ],
            options={
                'verbose_name': '成熟度检测结果',
                'verbose_name_plural': '成熟度检测结果',
            },
        ),
        migrations.CreateModel(
            name='PestDiseaseDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type', models.CharField(choices=[('healthy', '健康'), ('powdery_mildew', '白粉病'), ('rust', '锈病'), ('blight', '枯萎病'), ('leaf_spot', '叶斑病'), ('other', '其他')], default='healthy', max_length=20, verbose_name='病害类型')),
                ('disease_confidence', models.FloatField(blank=True, null=True, verbose_name='病害置信度')),
                ('pest_type', models.CharField(choices=[('no_pest', '无虫害'), ('aphid', '蚜虫'), ('beetle', '甲虫'), ('caterpillar', '毛虫'), ('mite', '螨虫'), ('other', '其他')], default='no_pest', max_length=20, verbose_name='虫害类型')),
                ('pest_confidence', models.FloatField(blank=True, null=True, verbose_name='虫害置信度')),
                ('detection_boxes', models.JSONField(blank=True, null=True, verbose_name='检测框数据')),
            ],
            options={
                'verbose_name': '病虫害检测结果',
                'verbose_name_plural': '病虫害检测结果',
            },
        ),
        migrations.CreateModel(
            name='RecognitionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('model_path', models.CharField(blank=True, max_length=255, verbose_name='模型路径')),
                ('confidence_threshold', models.FloatField(default=0.5, verbose_name='置信度阈值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '识别配置',
                'verbose_name_plural': '识别配置',
            },
        ),
        migrations.CreateModel(
            name='RecognitionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('crop_weed', '作物与杂草识别'), ('pest_disease', '病虫害检测'), ('maturity', '成熟度判断')], max_length=20, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recognition/images/', verbose_name='分析图像')),
                ('result_json', models.JSONField(blank=True, null=True, verbose_name='识别结果JSON')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='置信度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '识别任务',
                'verbose_name_plural': '识别任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
