# Generated by Django 6.0.3 on 2026-03-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_recognition', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitiontask',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_tasks', to='devices.robotdevice', verbose_name='设备'),
        ),
        migrations.AddField(
            model_name='pestdiseasedetection',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_disease_results', to='ai_recognition.recognitiontask', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='maturitydetection',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maturity_results', to='ai_recognition.recognitiontask', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='cropweeddetection',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_weed_results', to='ai_recognition.recognitiontask', verbose_name='任务'),
        ),
    ]
