# Generated by Django 6.0.3 on 2026-03-22 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recognition', '0002_initial'),
        ('devices', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('model_type', models.CharField(choices=[('yolov8n', 'YOLOv8 Nano'), ('yolov8s', 'YOLOv8 Small'), ('yolov8m', 'YOLOv8 Medium'), ('yolov8l', 'YOLOv8 Large'), ('yolov8x', 'YOLOv8 XLarge'), ('yolo11n', 'YOLO11 Nano'), ('yolo11s', 'YOLO11 Small'), ('yolo11m', 'YOLO11 Medium'), ('yolo11l', 'YOLO11 Large'), ('yolo11x', 'YOLO11 XLarge'), ('custom', '自定义模型')], default='yolov8n', max_length=20, verbose_name='模型架构')),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ai_models/', verbose_name='模型文件')),
                ('model_path', models.CharField(blank=True, max_length=500, verbose_name='模型路径')),
                ('description', models.TextField(blank=True, verbose_name='模型描述')),
                ('num_classes', models.IntegerField(default=0, verbose_name='类别数')),
                ('class_names', models.JSONField(blank=True, null=True, verbose_name='类别名称列表')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否默认')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='准确率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'AI模型',
                'verbose_name_plural': 'AI模型',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InferenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('image', '单张图片'), ('video', '视频文件'), ('camera', '实时摄像头')], default='image', max_length=20, verbose_name='推理模式')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='inference/source/', verbose_name='源文件')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='inference/result/', verbose_name='结果文件')),
                ('confidence_threshold', models.FloatField(default=0.25, verbose_name='置信度阈值')),
                ('total_detections', models.IntegerField(default=0, verbose_name='总检测数')),
                ('detection_details', models.JSONField(blank=True, null=True, verbose_name='检测详情')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='处理时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='推理时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inference_records', to='devices.robotdevice', verbose_name='关联设备')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_records', to='ai_recognition.aimodel', verbose_name='使用的模型')),
            ],
            options={
                'verbose_name': '推理记录',
                'verbose_name_plural': '推理记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='训练任务名称')),
                ('model_type', models.CharField(choices=[('yolov8n', 'YOLOv8 Nano'), ('yolov8s', 'YOLOv8 Small'), ('yolov8m', 'YOLOv8 Medium'), ('yolov8l', 'YOLOv8 Large'), ('yolov8x', 'YOLOv8 XLarge'), ('yolo11n', 'YOLO11 Nano'), ('yolo11s', 'YOLO11 Small'), ('yolo11m', 'YOLO11 Medium'), ('yolo11l', 'YOLO11 Large'), ('yolo11x', 'YOLO11 XLarge'), ('custom', '自定义模型')], default='yolov8n', max_length=20, verbose_name='基础模型')),
                ('dataset_path', models.CharField(max_length=500, verbose_name='数据集路径')),
                ('epochs', models.IntegerField(default=100, verbose_name='训练轮数')),
                ('batch_size', models.IntegerField(default=8, verbose_name='批次大小')),
                ('image_size', models.IntegerField(default=640, verbose_name='图像尺寸')),
                ('patience', models.IntegerField(default=20, verbose_name='早停耐心值')),
                ('device', models.CharField(default='0', max_length=50, verbose_name='训练设备')),
                ('optimizer', models.CharField(default='AdamW', max_length=50, verbose_name='优化器')),
                ('learning_rate', models.FloatField(default=0.001, verbose_name='学习率')),
                ('weight_decay', models.FloatField(default=0.0005, verbose_name='权重衰减')),
                ('momentum', models.FloatField(default=0.937, verbose_name='动量')),
                ('augment', models.BooleanField(default=True, verbose_name='数据增强')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '训练中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='训练进度(%)')),
                ('current_epoch', models.IntegerField(default=0, verbose_name='当前轮数')),
                ('best_map', models.FloatField(blank=True, null=True, verbose_name='最佳mAP')),
                ('output_dir', models.CharField(blank=True, max_length=500, verbose_name='输出目录')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('trained_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_tasks', to='ai_recognition.aimodel', verbose_name='训练好的模型')),
            ],
            options={
                'verbose_name': '训练任务',
                'verbose_name_plural': '训练任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
