# Generated by Django 6.0.3 on 2026-03-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_url', models.URLField(verbose_name='视频流地址')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃')], default='inactive', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('last_frame_time', models.DateTimeField(blank=True, null=True, verbose_name='最后帧时间')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_stream', to='devices.robotdevice', verbose_name='设备')),
            ],
            options={
                'verbose_name': '视频流',
                'verbose_name_plural': '视频流',
            },
        ),
        migrations.CreateModel(
            name='GPSLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='经度')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='海拔(m)')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='精度(m)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_locations', to='devices.robotdevice', verbose_name='设备')),
            ],
            options={
                'verbose_name': 'GPS位置',
                'verbose_name_plural': 'GPS位置',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device', '-recorded_at'], name='monitoring__device__e48a9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='温度(°C)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='湿度(%)')),
                ('light_intensity', models.FloatField(blank=True, null=True, verbose_name='光照强度(lux)')),
                ('soil_moisture', models.FloatField(blank=True, null=True, verbose_name='土壤墒情(%)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='经度')),
                ('speed', models.FloatField(default=0, verbose_name='速度(m/s)')),
                ('heading', models.FloatField(default=0, verbose_name='航向角(度)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='devices.robotdevice', verbose_name='设备')),
            ],
            options={
                'verbose_name': '传感器数据',
                'verbose_name_plural': '传感器数据',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device', '-recorded_at'], name='monitoring__device__2633e2_idx')],
            },
        ),
    ]
