# Generated by Django 6.0.3 on 2026-03-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('forward', '前进'), ('backward', '后退'), ('left', '左转'), ('right', '右转'), ('stop', '停止'), ('spray_start', '开始喷洒'), ('spray_stop', '停止喷洒'), ('speed_set', '设置速度'), ('mode_change', '切换模式')], max_length=20, verbose_name='命令类型')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='命令参数')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('sent', '已发送'), ('executing', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('response', models.TextField(blank=True, verbose_name='响应信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '控制命令',
                'verbose_name_plural': '控制命令',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活手动控制')),
                ('joystick_x', models.FloatField(default=0, verbose_name='摇杆X轴')),
                ('joystick_y', models.FloatField(default=0, verbose_name='摇杆Y轴')),
                ('spray_enabled', models.BooleanField(default=False, verbose_name='喷洒启用')),
                ('active_since', models.DateTimeField(blank=True, null=True, verbose_name='激活时间')),
            ],
            options={
                'verbose_name': '手动控制状态',
                'verbose_name_plural': '手动控制状态',
            },
        ),
    ]
